### PR TITLE
Update speakers

### PR DESCRIPTION
**Pull request by mathiasbynens**
@bterlson unfortunately won’t be able to make it. :(

### CODE REVIEW

**Comment by cramforce** [comment]
This is a generated file. We need to update this in the underlying spreadsheet. I believe that @janl is already on it!

**Comment by janl** [comment]
heya sorry, I had fixed this one the speaker’s page last Saturday, but not in the schedule, thanks for the heads up :)

**Comment by janl** [comment]
should be live in the next deploy

**Comment by mathiasbynens** [comment]
Thanks!

**Pull request closed without merging**
