### PR TITLE
pattern.svg reduced in size

### PR DESCRIPTION
**Pull request by Vaeshkar**
reduced anchor points and merged overlapping area's.

### CODE REVIEW

**Comment by cramforce** [comment]
Thanks!

@silkine Could you live with `pattern_reduce_2.svg`?

**Comment by silkine** [comment]
Hello @Vaeshkar, thank you very much for caring about file size. @malte In this case I'd prefer to rather go with the svg we have, that we have already reduced to 11kb with the help of svgomg . Further reduction would disintegrate the design concept of the forms, that we use in all other products that brand the conference. The clear geometric look of the snake and the rough edges of the paintbrushes are part of that concept just like the patterns.

This further reduction I feel, is a tad too drastic. 
gifmaker org_nzsjqi

**Comment by Vaeshkar** [comment]
There is always a middle road. We could look at that after jsconf18.

**Comment by cramforce** [comment]
We ended up merging a similar optimization from a different PR. Thanks @Vaeshkar !!

**Pull request closed without merging**
